# Task-02

# Import Libraries

In [98]:
import pandas as pd
import numpy as np

# Import the data

In [99]:
train_data = pd.read_csv(r"C:\Users\Aditya Dixit\Desktop\Writing works\PYTHON PRACTICE\Resolute AI task\Data\Task1and2\train.csv")

In [100]:
test_data = pd.read_csv(r"C:\Users\Aditya Dixit\Desktop\Writing works\PYTHON PRACTICE\Resolute AI task\Data\Task1and2\test.csv")

# Basic EDA & Cleaning

In [101]:
train_data

T1  T2  T3  T4  T5  T6  T7  T8  T9  T10  T11  T12  T13  T14  T15  T16  \
0     -70 -61 -66 -53 -51 -63 -82 -57 -76  -78  -66  -66  -61  -59  -73  -75   
1     -77 -74 -71 -76 -65 -63 -66 -52 -55  -75  -72  -75  -74  -61  -64  -63   
2     -53 -38 -55 -66 -62 -62 -65 -70 -62  -52  -56  -53  -66  -68  -72  -60   
3     -72 -62 -59 -65 -65 -65 -78 -82 -83  -59  -84  -60  -64  -83  -69  -72   
4     -67 -69 -65 -63 -59 -53 -70 -72 -71  -60  -61  -57  -54  -76  -61  -66   
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
36747 -68 -62 -64 -59 -59 -71 -67 -73 -73  -69  -71  -75  -56  -68  -68  -75   
36748 -56 -50 -57 -50 -59 -60 -62 -69 -58  -64  -49  -61  -58  -56  -60  -58   
36749 -42 -58 -72 -70 -75 -72 -76 -84 -84  -59  -65  -68  -65  -81  -86  -70   
36750 -50 -50 -70 -64 -64 -68 -68 -73 -79  -58  -61  -73  -67  -77  -73  -74   
36751 -66 -64 -70 -62 -59 -62 -53 -58 -64  -80  -73  -83  -67  -61  -56  -61   

       T17  T18 target  
0      -63  -77    B37  
1      -53  -63    B61  
2      -68  -77    A19  
3      -95  -73    A22  
4      -71  -80    A33  
...    ...  ...    ...  
36747  -75  -95    B34  
36748  -59  -64    B15  
36749  -75  -74     A6  
36750  -72  -81     B2  
36751  -67  -65    B45  

[36752 rows x 19 columns]

In [102]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36752 entries, 0 to 36751
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   T1      36752 non-null  int64 
 1   T2      36752 non-null  int64 
 2   T3      36752 non-null  int64 
 3   T4      36752 non-null  int64 
 4   T5      36752 non-null  int64 
 5   T6      36752 non-null  int64 
 6   T7      36752 non-null  int64 
 7   T8      36752 non-null  int64 
 8   T9      36752 non-null  int64 
 9   T10     36752 non-null  int64 
 10  T11     36752 non-null  int64 
 11  T12     36752 non-null  int64 
 12  T13     36752 non-null  int64 
 13  T14     36752 non-null  int64 
 14  T15     36752 non-null  int64 
 15  T16     36752 non-null  int64 
 16  T17     36752 non-null  int64 
 17  T18     36752 non-null  int64 
 18  target  36752 non-null  object
dtypes: int64(18), object(1)
memory usage: 5.3+ MB


In [103]:
train_data.describe()

T1            T2            T3            T4            T5  \
count  36752.000000  36752.000000  36752.000000  36752.000000  36752.000000   
mean     -65.865449    -64.521931    -64.574472    -65.296474    -64.462152   
std        8.737286      8.914559      8.154517      8.142803      8.068375   
min      -95.000000    -95.000000    -95.000000    -95.000000    -95.000000   
25%      -72.000000    -70.000000    -70.000000    -70.000000    -69.000000   
50%      -66.000000    -65.000000    -64.000000    -66.000000    -65.000000   
75%      -61.000000    -59.000000    -59.000000    -61.000000    -59.000000   
max      -41.000000    -37.000000    -41.000000    -39.000000    -36.000000   

                 T6            T7            T8            T9           T10  \
count  36752.000000  36752.000000  36752.000000  36752.000000  36752.000000   
mean     -63.318731    -67.030202    -66.591260    -65.692479    -65.555181   
std        8.651501      9.257529     10.160193     10.598247     10.408147   
min      -95.000000    -95.000000    -95.000000    -95.000000    -95.000000   
25%      -69.000000    -74.000000    -75.000000    -73.000000    -73.000000   
50%      -63.000000    -66.000000    -66.000000    -65.000000    -65.000000   
75%      -57.000000    -60.000000    -59.000000    -58.000000    -58.000000   
max      -39.000000    -45.000000    -39.000000    -39.000000    -37.000000   

                T11           T12           T13           T14           T15  \
count  36752.000000  36752.000000  36752.000000  36752.000000  36752.000000   
mean     -65.681922    -66.244204    -63.962614    -64.399080    -64.550011   
std        9.453958      8.866239      8.254217      9.562839      9.207343   
min      -95.000000    -95.000000    -95.000000    -95.000000    -95.000000   
25%      -71.000000    -72.000000    -69.000000    -70.000000    -70.000000   
50%      -65.000000    -66.000000    -63.000000    -64.000000    -65.000000   
75%      -59.000000    -61.000000    -58.000000    -58.000000    -58.000000   
max      -40.000000    -43.000000    -43.000000    -39.000000    -38.000000   

                T16           T17           T18  
count  36752.000000  36752.000000  36752.000000  
mean     -64.136782    -65.910726    -66.590417  
std       10.540542     10.071973     10.600992  
min      -95.000000    -95.000000    -95.000000  
25%      -71.000000    -72.000000    -74.000000  
50%      -63.000000    -65.000000    -66.000000  
75%      -57.000000    -59.000000    -59.000000  
max      -40.000000    -43.000000    -39.000000

In [104]:
test_data

T1  T2  T3  T4  T5  T6  T7  T8  T9  T10  T11  T12  T13  T14  T15  T16  \
0     -76 -83 -70 -66 -64 -72 -64 -69 -60  -76  -83  -78  -81  -81  -81  -70   
1     -58 -57 -78 -81 -73 -73 -78 -78 -82  -49  -55  -58  -66  -79  -72  -83   
2     -70 -70 -71 -69 -69 -68 -61 -55 -53  -82  -87  -76  -68  -57  -64  -75   
3     -71 -61 -56 -56 -61 -60 -68 -66 -72  -58  -55  -56  -58  -62  -61  -59   
4     -72 -71 -64 -69 -64 -63 -61 -42 -55  -61  -69  -67  -63  -63  -55  -49   
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
15747 -64 -68 -64 -67 -66 -53 -61 -51 -44  -76  -64  -62  -68  -60  -58  -54   
15748 -57 -46 -64 -55 -56 -54 -70 -64 -63  -51  -56  -58  -60  -61  -61  -62   
15749 -76 -67 -69 -71 -68 -70 -57 -57 -59  -76  -85  -72  -67  -58  -66  -66   
15750 -69 -78 -65 -65 -38 -55 -66 -66 -76  -64  -64  -66  -55  -60  -55  -64   
15751 -74 -68 -70 -80 -66 -61 -68 -62 -49  -79  -82  -71  -68  -74  -61  -57   

       T17  T18  
0      -60  -60  
1      -74  -80  
2      -57  -70  
3      -64  -65  
4      -49  -57  
...    ...  ...  
15747  -48  -51  
15748  -62  -64  
15749  -55  -54  
15750  -66  -69  
15751  -52  -56  

[15752 rows x 18 columns]

In [105]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15752 entries, 0 to 15751
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   T1      15752 non-null  int64
 1   T2      15752 non-null  int64
 2   T3      15752 non-null  int64
 3   T4      15752 non-null  int64
 4   T5      15752 non-null  int64
 5   T6      15752 non-null  int64
 6   T7      15752 non-null  int64
 7   T8      15752 non-null  int64
 8   T9      15752 non-null  int64
 9   T10     15752 non-null  int64
 10  T11     15752 non-null  int64
 11  T12     15752 non-null  int64
 12  T13     15752 non-null  int64
 13  T14     15752 non-null  int64
 14  T15     15752 non-null  int64
 15  T16     15752 non-null  int64
 16  T17     15752 non-null  int64
 17  T18     15752 non-null  int64
dtypes: int64(18)
memory usage: 2.2 MB


In [106]:
test_data.describe()

T1            T2            T3            T4            T5  \
count  15752.000000  15752.000000  15752.000000  15752.000000  15752.000000   
mean     -65.871191    -64.506539    -64.514030    -65.255523    -64.557770   
std        8.756142      9.016451      8.175667      8.179889      8.056777   
min      -95.000000    -95.000000    -95.000000    -95.000000    -95.000000   
25%      -72.000000    -70.000000    -70.000000    -70.000000    -69.000000   
50%      -66.000000    -65.000000    -64.000000    -66.000000    -65.000000   
75%      -61.000000    -58.000000    -59.000000    -61.000000    -60.000000   
max      -41.000000    -36.000000    -42.000000    -41.000000    -32.000000   

                T6            T7            T8            T9           T10  \
count  15752.00000  15752.000000  15752.000000  15752.000000  15752.000000   
mean     -63.27368    -67.047169    -66.730637    -65.725114    -65.526981   
std        8.58967      9.160641     10.190709     10.519560     10.443959   
min      -95.00000    -95.000000    -95.000000    -95.000000    -95.000000   
25%      -69.00000    -74.000000    -75.000000    -73.000000    -73.000000   
50%      -63.00000    -66.000000    -66.000000    -65.000000    -65.000000   
75%      -57.00000    -60.000000    -59.000000    -59.000000    -58.000000   
max      -39.00000    -46.000000    -40.000000    -39.000000    -41.000000   

                T11           T12           T13           T14           T15  \
count  15752.000000  15752.000000  15752.000000  15752.000000  15752.000000   
mean     -65.586338    -66.112430    -63.968068    -64.471115    -64.654393   
std        9.555815      8.922019      8.158542      9.463673      9.158459   
min      -95.000000    -95.000000    -95.000000    -95.000000    -95.000000   
25%      -71.000000    -72.000000    -69.000000    -70.000000    -70.000000   
50%      -65.000000    -65.000000    -63.000000    -64.000000    -65.000000   
75%      -59.000000    -60.000000    -58.000000    -58.000000    -59.000000   
max      -43.000000    -43.000000    -44.000000    -39.000000    -38.000000   

                T16           T17           T18  
count  15752.000000  15752.000000  15752.000000  
mean     -64.257110    -65.928390    -66.602844  
std       10.481551     10.000258     10.468128  
min      -95.000000    -95.000000    -95.000000  
25%      -71.000000    -72.000000    -74.000000  
50%      -63.000000    -65.000000    -66.000000  
75%      -57.000000    -59.000000    -60.000000  
max      -41.000000    -43.000000    -39.000000

Some observation from the EDA: -

- It seems like all values in the given data are negative integers.
- There are no null values in this table, so handling of that sort of datatype is not needed.
- Since all data values are negative integers, it does not really matter if we convert them into a positive integer or not.
- All the data values fall between (-100,0), so the dataset does not even need feature scaling. 

# Splitting the dataframe

In [107]:
# Independent Varible dataset
X = train_data.iloc[:, :-1].values
X

array([[-70, -61, -66, ..., -75, -63, -77],
       [-77, -74, -71, ..., -63, -53, -63],
       [-53, -38, -55, ..., -60, -68, -77],
       ...,
       [-42, -58, -72, ..., -70, -75, -74],
       [-50, -50, -70, ..., -74, -72, -81],
       [-66, -64, -70, ..., -61, -67, -65]], dtype=int64)

In [108]:
# Dependent Variable dataset
y = train_data.iloc[:, -1].values
y

array(['B37', 'B61', 'A19', ..., 'A6', 'B2', 'B45'], dtype=object)

In [109]:
# Train/Test = 80/20

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [110]:
X_train

array([[-80, -73, -68, ..., -58, -57, -55],
       [-55, -47, -54, ..., -73, -66, -66],
       [-64, -59, -62, ..., -50, -47, -63],
       ...,
       [-64, -63, -75, ..., -59, -64, -71],
       [-66, -74, -63, ..., -68, -73, -79],
       [-73, -82, -79, ..., -60, -51, -60]], dtype=int64)

In [111]:
X_test

array([[-56, -61, -79, ..., -66, -68, -81],
       [-52, -41, -59, ..., -61, -67, -69],
       [-62, -72, -59, ..., -65, -67, -62],
       ...,
       [-61, -72, -62, ..., -45, -45, -54],
       [-66, -64, -68, ..., -77, -77, -76],
       [-66, -61, -51, ..., -63, -69, -80]], dtype=int64)

In [112]:
y_train

array(['B80', 'A20', 'A68', ..., 'B45', 'A33', 'A61'], dtype=object)

In [113]:
y_test

array(['B27', 'A15', 'A36', ..., 'B60', 'A2', 'A26'], dtype=object)

# K Nearest Neighbour implementation on train.xlsx

In [114]:
# K Nearest Neighbour from the Scikit Learn Library

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

- K Nearest Neighbours - Predicting the labels/classification using X_test

In [115]:
y_pred = classifier.predict(X_test)

In [116]:
# Comparison: - y_pred vs y_test

compare = np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

pred_vs_test = pd.DataFrame(compare)

pred_vs_test

0    1
0     B27  B27
1     A15  A15
2     A36  A36
3     A76  A76
4     A57  A57
...   ...  ...
7346  B58  B58
7347  A46  A46
7348  B60  B60
7349   A2   A2
7350  A26  A26

[7351 rows x 2 columns]

- Confusion matrix & Accuracy - K Nearest Neighbours

In [117]:
# K Nearest Neighbours - Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

print(cm.shape)
print(cm)

(160, 160)
[[38  0  0 ...  0  0  0]
 [ 0 40  0 ...  0  0  0]
 [ 0  0 39 ...  0  0  0]
 ...
 [ 0  0  0 ... 45  0  0]
 [ 0  0  0 ...  0 46  0]
 [ 0  0  0 ...  0  0 43]]


In [118]:
# K Nearest Neighbours - Accuracy

knn_accuracy = (accuracy_score(y_test, y_pred))*100

print(knn_accuracy)

98.34036185552986


# K Nearest Neighbour implementation on test.xlsx

In [119]:
# Predicting the target values for required test_data
test_data_values = test_data.values

test_data_pred = classifier.predict(test_data_values)

In [120]:
# Printing the target values for required test_data
req_test_pred = pd.DataFrame(test_data_pred)
req_test_pred

0
0      B74
1      A10
2      B65
3      B20
4      A67
...    ...
15747  A71
15748  B11
15749  B69
15750  A38
15751  A80

[15752 rows x 1 columns]

# Random Forest implementation on train.xlsx

In [121]:
# Random Forest from the Scikit Learn Library

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

- Random Forest - Predicting the labels/classifications using X_test

In [122]:
y_pred = classifier.predict(X_test)

In [123]:
# Comparison: - y_pred vs y_test

compare1 = (np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

pred_vs_test1 = pd.DataFrame(compare1)

pred_vs_test1

0    1
0     B27  B27
1     A15  A15
2     A36  A36
3     A76  A76
4     A57  A57
...   ...  ...
7346  B58  B58
7347  A46  A46
7348  B60  B60
7349   A2   A2
7350  A26  A26

[7351 rows x 2 columns]

- Confusion matrix & Accuracy - K Nearest Neighbours

In [124]:
# Random Forest - Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm1 = confusion_matrix(y_test, y_pred)

print(cm1.shape)
print(cm1)


(160, 160)
[[37  0  0 ...  0  0  0]
 [ 0 41  0 ...  0  0  0]
 [ 0  0 39 ...  0  0  0]
 ...
 [ 0  0  0 ... 45  0  0]
 [ 0  0  0 ...  0 46  0]
 [ 0  0  0 ...  0  0 43]]


In [125]:
# Random Forest - Accuracy

rf_accuracy = (accuracy_score(y_test, y_pred))*100

print(rf_accuracy)

98.39477622092232


# Random Forest implementation on test.xlsx

In [126]:
# Predicting the target values for required test_data
test_data_values = test_data.values

test_data_pred = classifier.predict(test_data_values)

In [129]:
# Printing the target values for required test_data
req_test_pred1 = pd.DataFrame(test_data_pred)
req_test_pred1

0
0      B74
1      A10
2      B65
3      B20
4      A67
...    ...
15747  A71
15748  B11
15749  B69
15750  A38
15751  A80

[15752 rows x 1 columns]

# K Nearest Neighbours vs Random Forest

- ACCURACY

In [128]:
# K Nearest Neighbour vs Random Forest

print("K Nearest Neighbour Accuracy:", knn_accuracy)
print("Random Forest Accuracy:", rf_accuracy)

K Nearest Neighbour Accuracy: 98.34036185552986
Random Forest Accuracy: 98.39477622092232


- PREDICTED TARGET VALUE

In [130]:
# K Nearest Neighbour - TARGET VALUE

req_test_pred

0
0      B74
1      A10
2      B65
3      B20
4      A67
...    ...
15747  A71
15748  B11
15749  B69
15750  A38
15751  A80

[15752 rows x 1 columns]

In [132]:
# K Nearest Neighbour - TARGET VALUE
req_test_pred.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15752 entries, 0 to 15751
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       15752 non-null  object
dtypes: object(1)
memory usage: 123.2+ KB


In [133]:
# K Nearest Neighbour - TARGET VALUE
req_test_pred.describe()

0
count   15752
unique    160
top       A33
freq      273

In [131]:
# Random Forest - TARGET VALUE

req_test_pred1

0
0      B74
1      A10
2      B65
3      B20
4      A67
...    ...
15747  A71
15748  B11
15749  B69
15750  A38
15751  A80

[15752 rows x 1 columns]

In [134]:
# Random Forest - TARGET VALUE

req_test_pred1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15752 entries, 0 to 15751
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       15752 non-null  object
dtypes: object(1)
memory usage: 123.2+ KB


In [135]:
# Random Forest - TARGET VALUE

req_test_pred1.describe()

0
count   15752
unique    160
top       A33
freq      273

# Export the required outputs to csv

In [141]:
data = {'Accuracy': [float(knn_accuracy), float(rf_accuracy)]}

accuracy = pd.DataFrame(data, index=['K Nearest Neighbour', 'Random Forest'])

print(accuracy)

                      Accuracy
K Nearest Neighbour  98.340362
Random Forest        98.394776


In [142]:
accuracy.to_csv('KNN vs RF - ACCURACY.csv', index=False)

In [143]:
req_test_pred.to_csv('KNN-TargetValue.csv', index=False)

In [144]:
req_test_pred1.to_csv('RF-TargetValue.csv', index=False)